CREATE TABLE IF NOT EXISTS GAMES (
    id INT PRIMARY KEY,
    name VARCHAR(56),
    companyId INT
);

CREATE TABLE IF NOT EXISTS PLAYERS (
    id INT PRIMARY KEY,
    name VARCHAR(56),
    gamerTag VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS COMPANIES (
    id INT PRIMARY KEY,
    name VARCHAR(56)
);

CREATE TABLE IF NOT EXISTS PLAYERS_GAMES (
    playerId INT PRIMARY KEY,
    gameId INT PRIMARY KEY
);